export const instagram = "https://www.instagram.com/pajko0"
export const github = "https://github.com/xellu"
export const youtube = "https://youtube.com/@xellu"
export const discord = "https://discord.com/users/923528901219729430"
export const email = "mailto:me@xellu.tech"